### ISSUE TITLE
Repository license

### ISSUE THREAD

**Issue by Exanite** [martindevans/Myriad.ECS#2]
Hello! Would you be willing to add a license to your repo?

Based on this [StackExchange post](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license), having no license means that all rights are reserved and no one else can use the code in the repo. I respect your choice if that's what you intend, but adding a license would make it more clear if that's not the case.

Thank you!

**Comment by martindevans** [comment]
That's a good point, I'll add one shortly. Thanks for the reminder 👍

**Comment by martindevans** [comment]
Added MIT license: https://github.com/martindevans/Myriad.ECS/blob/master/license.md
